# -*- coding: utf-8 -*-
"""FK 인덱스 전면 보강 (launch-scale 성능) — 인덱스 없는 외래키 68종.

전 스키마 감사에서 FK 컬럼인데 그 컬럼을 선두로 하는 인덱스가 없는 것이 68건 나왔다.
인덱스 없는 FK 는 (1) 부모 삭제 시 자식 전체 seq-scan(cascade 지연·락 경합),
(2) 조인 성능 저하, (3) 갱신 시 락 경합을 부른다. 이번 세션에서 sys_history.actor_id·
sys_notification.user_id 로 사용자 삭제가 막히는 실제 통증을 세 번 겪었다(그 seq-scan 원인).

Postgres 관례대로 FK 를 전부 인덱싱한다. 현재 소량 데이터에서 인덱스 비용은 무시할 만하고,
성장하는 트랜잭션·감사 테이블에서 launch 후 위험을 없앤다. 검증 가능 —
tests/check_fk_indexes.py 가 인덱스 없는 FK 가 생기면 실패시킨다.

Revision ID: 0052_fk_indexes
Revises: 0051_ai_data_prep
"""
from alembic import op

revision = "0052_fk_indexes"
down_revision = "0051_ai_data_prep"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE INDEX IF NOT EXISTS ix_ai_developer_review_candidate_id ON ai_developer_review (candidate_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_ai_import_package_project_id ON ai_import_package (project_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_arrangement_code_base_drawing_id ON arrangement_code (base_drawing_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_arrangement_component_arrangement_id ON arrangement_component (arrangement_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_arrangement_component_join_macro_id ON arrangement_component (join_macro_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_arrangement_component_product_code_id ON arrangement_component (product_code_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_code_item_value_ref_table_id ON code_item_value (ref_table_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_com_supplier_eval_supplier_id ON com_supplier_eval (supplier_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_cpq_output_file_id ON cpq_output (file_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_cpq_output_run_id ON cpq_output (run_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_cpq_run_selection_id ON cpq_run (selection_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_cpq_selection_arrangement_id ON cpq_selection (arrangement_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_cpq_selection_product_code_id ON cpq_selection (product_code_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_cpq_selection_item_child_code_id ON cpq_selection_item (child_code_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_cpq_selection_item_parent_item_id ON cpq_selection_item (parent_item_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_cst_calc_run_id ON cst_calc (run_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_cst_price_part_id ON cst_price (part_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_cst_price_supplier_id ON cst_price (supplier_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_cst_quotation_customer_id ON cst_quotation (customer_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_cst_quotation_doc_file_id ON cst_quotation (doc_file_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_cst_quotation_pcr_id ON cst_quotation (pcr_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_cst_quotation_project_id ON cst_quotation (project_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_dev_requirement_image_req_id ON dev_requirement_image (req_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_doc_control_approver_id ON doc_control (approver_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_doc_control_customer_company_id ON doc_control (customer_company_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_dwg_approval_approver_id ON dwg_approval (approver_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_dwg_approval_drawing_id ON dwg_approval (drawing_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_dwg_approval_revision_id ON dwg_approval (revision_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_dwg_bom_part_id ON dwg_bom (part_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_dwg_dimension_macro_id ON dwg_dimension (macro_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_dwg_dimension_product_code_id ON dwg_dimension (product_code_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_dwg_document_drawing_id ON dwg_document (drawing_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_dwg_document_revision_id ON dwg_document (revision_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_dwg_file_drawing_id ON dwg_file (drawing_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_dwg_file_revision_id ON dwg_file (revision_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_dwg_part_relation_drawing_id ON dwg_part_relation (drawing_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_dwg_part_relation_value_macro_id ON dwg_part_relation (value_macro_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_dwg_supersedure_new_drawing_id ON dwg_supersedure (new_drawing_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_dwg_verification_drawing_id ON dwg_verification (drawing_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_dwg_verification_macro_id ON dwg_verification (macro_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_erp_po_item_po_id ON erp_po_item (po_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_erp_process_def_form_id ON erp_process_def (form_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_erp_process_edge_to_def_id ON erp_process_edge (to_def_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_erp_process_event_proc_def_id ON erp_process_event (proc_def_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_erp_warehouse_parent_id ON erp_warehouse (parent_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_erp_workflow_condition_edge_id ON erp_workflow_condition (edge_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_erp_workflow_condition_template_id ON erp_workflow_condition (template_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_erp_work_process_product_code_id ON erp_work_process (product_code_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_erp_work_process_supplier_id ON erp_work_process (supplier_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prj_project_customer_id ON prj_project (customer_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prj_project_manager_id ON prj_project (manager_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_product_code_base_drawing_id ON product_code (base_drawing_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_product_code_group_id ON product_code (group_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_product_code_item_source_item_id ON product_code_item (source_item_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prt_part_material_id ON prt_part (material_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prt_part_product_code_id ON prt_part (product_code_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prt_part_supplier_id ON prt_part (supplier_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prt_part_substitute_part_id ON prt_part_substitute (part_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prt_part_substitute_substitute_part_id ON prt_part_substitute (substitute_part_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prt_supplier_code_map_part_id ON prt_supplier_code_map (part_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_prt_supplier_code_map_product_code_id ON prt_supplier_code_map (product_code_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_sys_approval_request_requester_id ON sys_approval_request (requester_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_sys_history_actor_id ON sys_history (actor_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_sys_notification_user_id ON sys_notification (user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_sys_process_node_parent_id ON sys_process_node (parent_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_sys_role_permission_role_id ON sys_role_permission (role_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_sys_user_role_role_id ON sys_user_role (role_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_tbx_macro_ref_macro_id ON tbx_macro_ref (macro_id)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_ai_developer_review_candidate_id")
    op.execute("DROP INDEX IF EXISTS ix_ai_import_package_project_id")
    op.execute("DROP INDEX IF EXISTS ix_arrangement_code_base_drawing_id")
    op.execute("DROP INDEX IF EXISTS ix_arrangement_component_arrangement_id")
    op.execute("DROP INDEX IF EXISTS ix_arrangement_component_join_macro_id")
    op.execute("DROP INDEX IF EXISTS ix_arrangement_component_product_code_id")
    op.execute("DROP INDEX IF EXISTS ix_code_item_value_ref_table_id")
    op.execute("DROP INDEX IF EXISTS ix_com_supplier_eval_supplier_id")
    op.execute("DROP INDEX IF EXISTS ix_cpq_output_file_id")
    op.execute("DROP INDEX IF EXISTS ix_cpq_output_run_id")
    op.execute("DROP INDEX IF EXISTS ix_cpq_run_selection_id")
    op.execute("DROP INDEX IF EXISTS ix_cpq_selection_arrangement_id")
    op.execute("DROP INDEX IF EXISTS ix_cpq_selection_product_code_id")
    op.execute("DROP INDEX IF EXISTS ix_cpq_selection_item_child_code_id")
    op.execute("DROP INDEX IF EXISTS ix_cpq_selection_item_parent_item_id")
    op.execute("DROP INDEX IF EXISTS ix_cst_calc_run_id")
    op.execute("DROP INDEX IF EXISTS ix_cst_price_part_id")
    op.execute("DROP INDEX IF EXISTS ix_cst_price_supplier_id")
    op.execute("DROP INDEX IF EXISTS ix_cst_quotation_customer_id")
    op.execute("DROP INDEX IF EXISTS ix_cst_quotation_doc_file_id")
    op.execute("DROP INDEX IF EXISTS ix_cst_quotation_pcr_id")
    op.execute("DROP INDEX IF EXISTS ix_cst_quotation_project_id")
    op.execute("DROP INDEX IF EXISTS ix_dev_requirement_image_req_id")
    op.execute("DROP INDEX IF EXISTS ix_doc_control_approver_id")
    op.execute("DROP INDEX IF EXISTS ix_doc_control_customer_company_id")
    op.execute("DROP INDEX IF EXISTS ix_dwg_approval_approver_id")
    op.execute("DROP INDEX IF EXISTS ix_dwg_approval_drawing_id")
    op.execute("DROP INDEX IF EXISTS ix_dwg_approval_revision_id")
    op.execute("DROP INDEX IF EXISTS ix_dwg_bom_part_id")
    op.execute("DROP INDEX IF EXISTS ix_dwg_dimension_macro_id")
    op.execute("DROP INDEX IF EXISTS ix_dwg_dimension_product_code_id")
    op.execute("DROP INDEX IF EXISTS ix_dwg_document_drawing_id")
    op.execute("DROP INDEX IF EXISTS ix_dwg_document_revision_id")
    op.execute("DROP INDEX IF EXISTS ix_dwg_file_drawing_id")
    op.execute("DROP INDEX IF EXISTS ix_dwg_file_revision_id")
    op.execute("DROP INDEX IF EXISTS ix_dwg_part_relation_drawing_id")
    op.execute("DROP INDEX IF EXISTS ix_dwg_part_relation_value_macro_id")
    op.execute("DROP INDEX IF EXISTS ix_dwg_supersedure_new_drawing_id")
    op.execute("DROP INDEX IF EXISTS ix_dwg_verification_drawing_id")
    op.execute("DROP INDEX IF EXISTS ix_dwg_verification_macro_id")
    op.execute("DROP INDEX IF EXISTS ix_erp_po_item_po_id")
    op.execute("DROP INDEX IF EXISTS ix_erp_process_def_form_id")
    op.execute("DROP INDEX IF EXISTS ix_erp_process_edge_to_def_id")
    op.execute("DROP INDEX IF EXISTS ix_erp_process_event_proc_def_id")
    op.execute("DROP INDEX IF EXISTS ix_erp_warehouse_parent_id")
    op.execute("DROP INDEX IF EXISTS ix_erp_workflow_condition_edge_id")
    op.execute("DROP INDEX IF EXISTS ix_erp_workflow_condition_template_id")
    op.execute("DROP INDEX IF EXISTS ix_erp_work_process_product_code_id")
    op.execute("DROP INDEX IF EXISTS ix_erp_work_process_supplier_id")
    op.execute("DROP INDEX IF EXISTS ix_prj_project_customer_id")
    op.execute("DROP INDEX IF EXISTS ix_prj_project_manager_id")
    op.execute("DROP INDEX IF EXISTS ix_product_code_base_drawing_id")
    op.execute("DROP INDEX IF EXISTS ix_product_code_group_id")
    op.execute("DROP INDEX IF EXISTS ix_product_code_item_source_item_id")
    op.execute("DROP INDEX IF EXISTS ix_prt_part_material_id")
    op.execute("DROP INDEX IF EXISTS ix_prt_part_product_code_id")
    op.execute("DROP INDEX IF EXISTS ix_prt_part_supplier_id")
    op.execute("DROP INDEX IF EXISTS ix_prt_part_substitute_part_id")
    op.execute("DROP INDEX IF EXISTS ix_prt_part_substitute_substitute_part_id")
    op.execute("DROP INDEX IF EXISTS ix_prt_supplier_code_map_part_id")
    op.execute("DROP INDEX IF EXISTS ix_prt_supplier_code_map_product_code_id")
    op.execute("DROP INDEX IF EXISTS ix_sys_approval_request_requester_id")
    op.execute("DROP INDEX IF EXISTS ix_sys_history_actor_id")
    op.execute("DROP INDEX IF EXISTS ix_sys_notification_user_id")
    op.execute("DROP INDEX IF EXISTS ix_sys_process_node_parent_id")
    op.execute("DROP INDEX IF EXISTS ix_sys_role_permission_role_id")
    op.execute("DROP INDEX IF EXISTS ix_sys_user_role_role_id")
    op.execute("DROP INDEX IF EXISTS ix_tbx_macro_ref_macro_id")
